# -*- coding: utf-8 -*-
from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(343, 118)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Settings.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Settings)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Settings)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboFont = QtWidgets.QFontComboBox(Settings)
        self.comboFont.setObjectName("comboFont")
        self.gridLayout.addWidget(self.comboFont, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Settings)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.spinFontSize = QtWidgets.QDoubleSpinBox(Settings)
        self.spinFontSize.setMaximum(100.0)
        self.spinFontSize.setObjectName("spinFontSize")
        self.gridLayout.addWidget(self.spinFontSize, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Settings)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.spinTab = QtWidgets.QSpinBox(Settings)
        self.spinTab.setPrefix("")
        self.spinTab.setMinimum(0)
        self.spinTab.setMaximum(100)
        self.spinTab.setProperty("value", 4)
        self.spinTab.setObjectName("spinTab")
        self.gridLayout.addWidget(self.spinTab, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnCancel = QtWidgets.QPushButton(Settings)
        self.btnCancel.setAutoDefault(False)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.btnSave = QtWidgets.QPushButton(Settings)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        Settings.setWindowTitle(QtWidgets.QApplication.translate("Settings", "Configuración", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Settings", "Tipografía:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Settings", "Tamaño:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Settings", "Tabulador:", None, -1))
        self.spinTab.setSuffix(QtWidgets.QApplication.translate("Settings", " espacios", None, -1))
        self.btnCancel.setText(QtWidgets.QApplication.translate("Settings", "Cancelar", None, -1))
        self.btnSave.setText(QtWidgets.QApplication.translate("Settings", "Guardar", None, -1))

from icons import icons
